AWSTemplateFormatVersion: 2010-09-09
Description: |
  DynamoDB and related resourcs to be used with portfolio.

Resources:
  PortfolioTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: "portfolioSection"
          AttributeType: "S"
        - AttributeName: "itemOrder"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification:
        Enabled: false
      DeletionProtectionEnabled: true
      KeySchema: # Required
        - AttributeName: "portfolioSection"
          KeyType: "HASH"
        - AttributeName: "itemOrder"
          KeyType: "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TableName: "portfolio"
      Tags: 
        - Key: "infra-group"
          Value: "portfolio"