AWSTemplateFormatVersion: 2010-09-09
Description: |
  DynamoDB and related resourcs to be used with portfolio.
Parameters:
  
Resources:
  Portfolio-Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: "String"
          AttributeType: "String"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification:
        Enabled: false
      DeletionProtectionEnabled: true
      KeySchema: # Required
        - AttributeName: "portfolioSection"
          KeyType: "Hash"
        - AttributeName: "itemOrder"
          KeyType: "Range"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TableName: "portfolio"
      Tags: 
        - Key: "infra-group"
          Value: "portfolio"
  
Outputs: