name: Foundation Infrastructure Deployment

on: workflow_dispatch

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read 

jobs:
  FoundationDeployment:
    runs-on: ubuntu-latest
    environment: AWS Production
    name: Create foundation resources
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: DomainCertificate - Deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: DomainCertificate
          template: Foundation/certificate.yaml
          parameter-overrides: >-
            HostedZoneId=${{secrets.HOSTED_ZONE_ID}}
          no-fail-on-empty-changeset: "1"